broxus/nekoton_bridge

packages/nekoton_bridge/native/src/nekoton_wrapper/mod.rs
Just one tiny rust warning was fixed :)
=> fix: the last rust warning

packages/nekoton_bridge/pubspec.yaml, packages/nekoton_bridge/test/money2_test.dart
Just add money2, money2_improver and tests to the package.
=> feat: add money2 and money2_improver

CHANGELOG.md, melos.yaml, packages/flutter_nekoton_bridge/CHANGELOG.md, packages/flutter_nekoton_bridge/android/CMakeLists.txt, packages/flutter_nekoton_bridge/example/.gitignore, packages/flutter_nekoton_bridge/example/CHANGELOG.md, packages/flutter_nekoton_bridge/example/pubspec.yaml, packages/flutter_nekoton_bridge/ios/flutter_nekoton_bridge.podspec, packages/flutter_nekoton_bridge/linux/CMakeLists.txt, packages/flutter_nekoton_bridge/macos/flutter_nekoton_bridge.podspec, packages/flutter_nekoton_bridge/pubspec.yaml, packages/flutter_nekoton_bridge/windows/CMakeLists.txt, packages/nekoton_bridge/CHANGELOG.md, packages/nekoton_bridge/native/src/utils/caller.rs, packages/nekoton_bridge/pubspec.yaml, pubspec.yaml, scripts/build-android.sh, scripts/build-apple.sh, scripts/build-other.sh
Migration was done [using howto.](https://melos.invertase.dev/guides/migrations#200-to-300)
You **SHOULD** upgrade global melos installation:
```sh
dart pub global activate melos
```
=> Feat: melos upgrade

packages/flutter_nekoton_bridge/example/integration_test/logger_test.dart, packages/flutter_nekoton_bridge/example/lib/main.dart, packages/flutter_nekoton_bridge/ios/Classes/frb.h, packages/flutter_nekoton_bridge/lib/flutter_nekoton_bridge.dart, packages/flutter_nekoton_bridge/lib/tests_related/test_logger.dart, packages/flutter_nekoton_bridge/lib/tests_related/tests_related_lib.dart, packages/nekoton_bridge/lib/src/bridge_generated.dart, packages/nekoton_bridge/lib/src/bridge_generated.io.dart, packages/nekoton_bridge/lib/src/bridge_generated.web.dart, packages/nekoton_bridge/native/src/bridge_generated.rs, packages/nekoton_bridge/native/src/merged.rs, packages/nekoton_bridge/native/src/utils/tests_api.rs
And it doesn't test **panic** yet :(
=> feat: add logger test

Cargo.lock, packages/nekoton_bridge/native/Cargo.toml, scripts/pre-bs.sh
* Fix nekoton version by tag ([Rexagon](https://github.com/Rexagon) thank you for your support!)
* Fix pre-bs script (melos prints 'there is a new version of melos' and it breaks the script)
=> fix: upgrade rust libs, fix pre-bs script

packages/flutter_nekoton_bridge/example/integration_test/transport/gql_transport_test.dart, packages/flutter_nekoton_bridge/example/integration_test/transport/jrpc_transport_test.dart
=> fix: transport tests

CHANGELOG.md, packages/flutter_nekoton_bridge/CHANGELOG.md, packages/flutter_nekoton_bridge/android/CMakeLists.txt, packages/flutter_nekoton_bridge/example/CHANGELOG.md, packages/flutter_nekoton_bridge/example/pubspec.yaml, packages/flutter_nekoton_bridge/ios/flutter_nekoton_bridge.podspec, packages/flutter_nekoton_bridge/linux/CMakeLists.txt, packages/flutter_nekoton_bridge/macos/flutter_nekoton_bridge.podspec, packages/flutter_nekoton_bridge/pubspec.yaml, packages/flutter_nekoton_bridge/windows/CMakeLists.txt, packages/nekoton_bridge/CHANGELOG.md, packages/nekoton_bridge/pubspec.yaml
- flutter_nekoton_bridge@1.8.0-dev.7
- flutter_nekoton_bridge_example@1.8.0-dev.7
- nekoton_bridge@1.8.0-dev.6
=> chore(release): publish packages

packages/flutter_nekoton_bridge/example/integration_test/core/accounts_storage_test.dart, packages/flutter_nekoton_bridge/example/integration_test/core/keystore_test.dart, packages/flutter_nekoton_bridge/example/integration_test/core/ton_wallet_test.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/accounts_storage/accounts_storage.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/keystore/keystore.dart
- Change return type of add/remove methods to return ONLY PublicKey/Address of instance.
- Update methods do not return anything
- Fix tests for new logic
=> feat: update keystore and accountsstorage logic

packages/flutter_nekoton_bridge/example/pubspec.yaml, packages/nekoton_bridge/pubspec.yaml
Just update some libs (thanx, dependabot!).
=> chore: update libs

CHANGELOG.md, packages/flutter_nekoton_bridge/CHANGELOG.md, packages/flutter_nekoton_bridge/android/CMakeLists.txt, packages/flutter_nekoton_bridge/example/CHANGELOG.md, packages/flutter_nekoton_bridge/example/pubspec.yaml, packages/flutter_nekoton_bridge/ios/flutter_nekoton_bridge.podspec, packages/flutter_nekoton_bridge/linux/CMakeLists.txt, packages/flutter_nekoton_bridge/macos/flutter_nekoton_bridge.podspec, packages/flutter_nekoton_bridge/pubspec.yaml, packages/flutter_nekoton_bridge/windows/CMakeLists.txt, packages/nekoton_bridge/CHANGELOG.md, packages/nekoton_bridge/pubspec.yaml
- flutter_nekoton_bridge@1.8.0-dev.12
- nekoton_bridge@1.8.0-dev.10
- flutter_nekoton_bridge_example@1.8.0-dev.12
=> chore(release): publish packages (#133)

packages/flutter_nekoton_bridge/example/integration_test/core/generic_contract_test.dart, packages/flutter_nekoton_bridge/example/integration_test/core/token_wallet_test.dart, packages/flutter_nekoton_bridge/example/integration_test/core/ton_wallet_test.dart
- Add tests for multi-subscribing and disposing
=> feat: add tests for multi-subscribing

packages/flutter_nekoton_bridge/lib/nekoton/core/generic_contract/generic_contract.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/token_wallet/token_wallet.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/ton_wallet.dart
=> fix: updating data after dispose

README.md, packages/flutter_nekoton_bridge/README.md, packages/nekoton_bridge/README.md, scripts/version.sh
=> chore: update readme

packages/nekoton_bridge/native/src/nekoton_wrapper/core/keystore/mod.rs
=> fix: base64 string encoding

.github/workflows/publish-release-fnb.yml, .github/workflows/publish-release-nb.yml
**READY**
separate nb & fnb release workflows
=> ci: separate nb & fnb release workflows

packages/flutter_nekoton_bridge/example/integration_test/transport/jrpc_transport_test.dart, packages/nekoton_bridge/native/Cargo.toml
=> fix: nekoton_block venom feature

packages/flutter_nekoton_bridge/lib/example_related/caller_wrapper.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/accounts_storage/models/assets_list.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/accounts_storage/models/assets_list.freezed.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/core_lib.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/generic_contract/generic_contract.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/generic_contract/generic_contract.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/refreshing_interface.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/token_wallet/token_wallet.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/token_wallet/token_wallet.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/ton_wallet.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/ton_wallet.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/external/gql_connection.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/external/jrpc_connection.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/external/ledger_connection.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/external/storage.reflectable.dart
=> feat: add refresing interface

packages/flutter_nekoton_bridge/lib/nekoton/core/keystore/keystore.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/models/pending_transaction.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/models/pending_transaction.freezed.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/models/pending_transaction.g.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/models/transaction.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/models/transaction.freezed.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/models/transaction.g.dart, packages/flutter_nekoton_bridge/lib/nekoton/crypto/models/signed_message.dart, packages/flutter_nekoton_bridge/lib/nekoton/crypto/models/signed_message.freezed.dart, packages/flutter_nekoton_bridge/lib/nekoton/crypto/models/signed_message.g.dart, packages/flutter_nekoton_bridge/lib/nekoton/crypto/unsigned_message.dart, packages/flutter_nekoton_bridge/lib/nekoton/helpers/abi.dart, packages/flutter_nekoton_bridge/lib/nekoton/transport/gql_transport.dart, packages/flutter_nekoton_bridge/lib/nekoton/utils.dart, packages/nekoton_bridge/lib/src/bridge_generated.dart, packages/nekoton_bridge/native/src/nekoton_wrapper/crypto/crypto_api.rs, packages/nekoton_bridge/native/src/nekoton_wrapper/crypto/models.rs, packages/nekoton_bridge/native/src/nekoton_wrapper/helpers/abi_api.rs, packages/nekoton_bridge/native/src/nekoton_wrapper/transport/gql_transport_api.rs, packages/nekoton_bridge/native/src/nekoton_wrapper/transport/mod.rs
=> fix: transport timeout

packages/flutter_nekoton_bridge/lib/nekoton/utils.dart
**READY**
Just add Uri to/from json converter.
=> feat: add Uri converter

packages/flutter_nekoton_bridge/pubspec.yaml, packages/flutter_nekoton_bridge/test/nekoton_briddge_test.dart, packages/nekoton_bridge/lib/src/ffi.dart
=> feat: allow mocking bridge

packages/flutter_nekoton_bridge/lib/nekoton/core/generic_contract/generic_contract.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/token_wallet/token_wallet.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/ton_wallet.dart
=> feat: replace StreamController to BehaviorSubject

packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/models/de_pool_on_round_complete_notification.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/models/de_pool_on_round_complete_notification.freezed.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/models/de_pool_on_round_complete_notification.g.dart
=> feat: replace string to bigint

packages/flutter_nekoton_bridge/lib/nekoton/core/token_wallet/token_wallet.dart
=> chore: fix refresh description

packages/nekoton_bridge/lib/nekoton_bridge.dart
=> feat: add providing FfiException above

packages/flutter_nekoton_bridge/lib/nekoton/core/models/internal_message.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/models/internal_message.freezed.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/models/internal_message.g.dart
=> feat: fix address type

.github/workflows/build.yml, .github/workflows/create-release.yml, .github/workflows/publish-release-fnb.yml, .github/workflows/publish-release-nb.yml, packages/flutter_nekoton_bridge/analysis_options.yaml, packages/flutter_nekoton_bridge/example/pubspec.yaml, packages/flutter_nekoton_bridge/pubspec.yaml, packages/nekoton_bridge/lib/src/bridge_generated.io.dart, packages/nekoton_bridge/pubspec.yaml
=> chore: upgrade libs

CHANGELOG.md, README.md, packages/flutter_nekoton_bridge/CHANGELOG.md, packages/flutter_nekoton_bridge/README.md, packages/flutter_nekoton_bridge/android/CMakeLists.txt, packages/flutter_nekoton_bridge/example/CHANGELOG.md, packages/flutter_nekoton_bridge/example/pubspec.yaml, packages/flutter_nekoton_bridge/ios/flutter_nekoton_bridge.podspec, packages/flutter_nekoton_bridge/linux/CMakeLists.txt, packages/flutter_nekoton_bridge/macos/flutter_nekoton_bridge.podspec, packages/flutter_nekoton_bridge/pubspec.yaml, packages/flutter_nekoton_bridge/windows/CMakeLists.txt, packages/nekoton_bridge/CHANGELOG.md, packages/nekoton_bridge/README.md, packages/nekoton_bridge/pubspec.yaml
**READY**
Empty commit for melos version bump.
=> feat: nope (empty commit for melos)

.github/workflows/build.yml, .github/workflows/publish-release-fnb.yml, .github/workflows/publish-release-nb.yml
**READY**
This PR fixed rust version (workaround).
=> fix: fix rust version

packages/flutter_nekoton_bridge/pubspec.yaml, packages/nekoton_bridge/pubspec.yaml
**READY**
Chore PR: upgrade money2 and money2_improver.
=> chore: upgrade money2 and money2_improver

.github/workflows/build.yml, .github/workflows/publish-release-fnb.yml, .github/workflows/publish-release-nb.yml
**READY**
Add rust toolchain version (because it doesn't work without it).
=> fix: rust toolchain version

packages/flutter_nekoton_bridge/example/integration_test/transport/gql_transport_test.dart, packages/flutter_nekoton_bridge/example/integration_test/transport/proto_transport_test.dart, packages/flutter_nekoton_bridge/ios/Classes/frb.h, packages/flutter_nekoton_bridge/lib/nekoton/crypto/unsigned_message.dart, packages/flutter_nekoton_bridge/lib/nekoton/helpers/abi.dart, packages/nekoton_bridge/lib/src/bridge_generated.dart, packages/nekoton_bridge/lib/src/bridge_generated.io.dart, packages/nekoton_bridge/lib/src/bridge_generated.web.dart, packages/nekoton_bridge/native/src/nekoton_wrapper/crypto/crypto_api.rs, packages/nekoton_bridge/native/src/nekoton_wrapper/crypto/models.rs, packages/nekoton_bridge/native/src/nekoton_wrapper/helpers/abi_api.rs, packages/nekoton_bridge/native/src/nekoton_wrapper/helpers/mod.rs, packages/nekoton_bridge/native/src/nekoton_wrapper/transport/mod.rs
**READY**
- Implemented more abi methods: `parseFullAccountBoc`, `makeFullAccountBoc`, `encodeInternalMessage`, `createRawExternalMessage`
- Added `dispose` and `signFake` methods for `UnsignedMessage`
=> feat: implement more abi methods

packages/flutter_nekoton_bridge/lib/nekoton/utils.dart
=> fix: remove isUtc from DateTimeJsonConverter

packages/nekoton_bridge/pubspec.yaml
**READY**
Fix flutter_rust_bridge version to exact.
=> fix: fix flutter_rust_bridge version to exact

.github/workflows/publish-release-nb.yml, packages/flutter_nekoton_bridge/README.md, packages/nekoton_bridge/README.md
**READY**
Empty PR just to satisfy melos version
=> feat: empty

packages/flutter_nekoton_bridge/ios/Classes/frb.h, packages/flutter_nekoton_bridge/lib/flutter_nekoton_bridge.dart, packages/nekoton_bridge/lib/src/bridge_generated.dart, packages/nekoton_bridge/lib/src/bridge_generated.io.dart, packages/nekoton_bridge/lib/src/bridge_generated.web.dart, packages/nekoton_bridge/native/src/nekoton_wrapper/helpers/abi_api.rs, packages/nekoton_bridge/native/src/nekoton_wrapper/mod.rs, packages/nekoton_bridge/native/src/utils/api.rs, packages/nekoton_bridge/native/src/utils/logger.rs
**READY**
Use Clock instead of SystemTime and provide time offset from outside the packet.
=> feat: add clock offset

packages/flutter_nekoton_bridge/lib/flutter_nekoton_bridge.dart
**READY**
Just a tiny type fix.
=> fix: updateClockOffset param changed to Duration

packages/flutter_nekoton_bridge/lib/nekoton/external/proto_connection.dart
**READY**
Just a tiny fix for content type in the protobuf http header.
=> fix: http header for protobuf

packages/flutter_nekoton_bridge/lib/flutter_nekoton_bridge.dart, packages/flutter_nekoton_bridge/lib/log_entry.dart, packages/nekoton_bridge/lib/src/bridge_generated.dart, packages/nekoton_bridge/native/src/utils/logger.rs
=> feat: add stacktrace to LogEntry

packages/flutter_nekoton_bridge/lib/nekoton/core/generic_contract/generic_contract.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/token_wallet/token_wallet.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/ton_wallet.dart, packages/flutter_nekoton_bridge/lib/nekoton/transport/gql_transport.dart, packages/flutter_nekoton_bridge/lib/nekoton/transport/jrpc_transport.dart, packages/flutter_nekoton_bridge/lib/nekoton/transport/proto_transport.dart, packages/flutter_nekoton_bridge/lib/nekoton/transport/transport.dart, packages/flutter_nekoton_bridge/lib/rust_to_dart/rust_to_dart_caller.dart
=> fix: added disposed flag to transport

Cargo.lock, packages/flutter_nekoton_bridge/example/integration_test/core/ton_wallet_test.dart, packages/flutter_nekoton_bridge/ios/Classes/frb.h, packages/flutter_nekoton_bridge/lib/example_related/caller_wrapper.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/generic_contract/generic_contract.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/generic_contract/generic_contract.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/jetton_wallet/jetton_wallet.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/token_wallet/token_wallet.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/models/models.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/models/transaction_execution_options.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/models/transaction_execution_options.freezed.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/models/transaction_execution_options.g.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/ton_wallet.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/ton_wallet.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/core/ton_wallet/ton_wallet_lib.dart, packages/flutter_nekoton_bridge/lib/nekoton/external/gql_connection.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/external/jrpc_connection.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/external/ledger_connection.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/external/proto_connection.reflectable.dart, packages/flutter_nekoton_bridge/lib/nekoton/external/storage.reflectable.dart, packages/nekoton_bridge/lib/src/api/merged.dart, packages/nekoton_bridge/lib/src/frb_generated.dart, packages/nekoton_bridge/lib/src/frb_generated.io.dart, packages/nekoton_bridge/lib/src/frb_generated.web.dart, packages/nekoton_bridge/rust/src/nekoton_wrapper/core/generic_contract/generic_contract_api.rs, packages/nekoton_bridge/rust/src/nekoton_wrapper/core/generic_contract/mod.rs, packages/nekoton_bridge/rust/src/nekoton_wrapper/core/ton_wallet/mod.rs, packages/nekoton_bridge/rust/src/nekoton_wrapper/core/ton_wallet/ton_wallet_api.rs
=> feat: add execution options to estimateFees and update related models

Cargo.lock, packages/flutter_nekoton_bridge/example/integration_test/abi_test.dart, packages/flutter_nekoton_bridge/ios/Classes/frb.h, packages/flutter_nekoton_bridge/lib/nekoton/helpers/abi.dart, packages/nekoton_bridge/lib/src/api/merged.dart, packages/nekoton_bridge/lib/src/frb_generated.dart, packages/nekoton_bridge/lib/src/frb_generated.io.dart, packages/nekoton_bridge/lib/src/frb_generated.web.dart, packages/nekoton_bridge/rust/src/nekoton_wrapper/helpers/abi_api.rs, packages/nekoton_bridge/rust/src/nekoton_wrapper/helpers/mod.rs
=> feat: add encodeComment function
